"""Loads the Maryland 2026 election calendar (primary + general) and their
verified deadlines into the elections/deadlines tables. Dates are sourced
from the Maryland State Board of Elections and documented in
docs/election-research-notes.md -- do not add a date here without updating
that doc, and do not guess dates that weren't confirmed in research (e.g.
the general ballot certification date, which was not published as of
2026-07-02).

Usage:
    python3 scripts/load_md_2026_elections_calendar.py > out.sql
"""
import sys

CALENDAR_SOURCE_URL = "https://elections.maryland.gov/elections/2026/index.html"
SOURCE_ID = "44444444-4444-4444-4444-444444444444"
PRIMARY_ELECTION_ID = "22222222-2222-2222-2222-222222222222"  # created in task 3
GENERAL_ELECTION_ID = "55555555-5555-5555-5555-555555555555"


def dq(value: str, tag: str = "q") -> str:
    return f"${tag}${value}${tag}$"


def sql_text(value):
    return "null" if value is None else dq(str(value))


def main():
    out = sys.stdout
    out.write("-- Generated by scripts/load_md_2026_elections_calendar.py. Idempotent: safe to re-run.\n\n")

    out.write(
        "insert into sources (source_id, source_url, source_type, effective_date, confidence, notes)\n"
        f"values ('{SOURCE_ID}', {sql_text(CALENDAR_SOURCE_URL)}, {sql_text('election_calendar')}, "
        "'2026-07-02', 0.8, "
        f"{sql_text('MD 2026 calendar, verified via web search 2026-07-02; see docs/election-research-notes.md')})\n"
        "on conflict (source_id) do nothing;\n\n"
    )

    # Primary election already exists (created in task 3 loading the Montgomery
    # BS DEM 125 ballot). It was originally tagged party_scope='Democratic',
    # which is wrong: the primary event itself covers all parties'  ballots
    # (party lives on ballot_styles, not on the election). Fix that here.
    out.write(
        f"update elections set party_scope = null where election_id = '{PRIMARY_ELECTION_ID}';\n\n"
    )

    out.write(
        "insert into deadlines (election_id, deadline_type, deadline_at, source_id, notes)\n"
        "values\n"
        f"  ('{PRIMARY_ELECTION_ID}', 'early_voting_start', '2026-06-11T07:00:00-04:00', '{SOURCE_ID}', null),\n"
        f"  ('{PRIMARY_ELECTION_ID}', 'early_voting_end', '2026-06-18T20:00:00-04:00', '{SOURCE_ID}', null),\n"
        f"  ('{PRIMARY_ELECTION_ID}', 'election_day', '2026-06-23T20:00:00-04:00', '{SOURCE_ID}', "
        f"{sql_text('polls close 8pm; ballot certified 2026-04-14 per EL section 9-207(a)(2)')})\n"
        "on conflict (election_id, deadline_type) do nothing;\n\n"
    )

    out.write(
        "insert into elections (election_id, name, election_type, election_date, state, jurisdiction_scope, "
        "party_scope, is_special, status, source_id)\n"
        f"values ('{GENERAL_ELECTION_ID}', {sql_text('2026 General Election')}, 'general', '2026-11-03', "
        f"'MD', 'state', null, false, 'scheduled', '{SOURCE_ID}')\n"
        "on conflict (election_id) do nothing;\n\n"
    )

    out.write(
        "insert into deadlines (election_id, deadline_type, deadline_at, source_id, notes)\n"
        "values\n"
        f"  ('{GENERAL_ELECTION_ID}', 'candidate_filing_deadline_nonprincipal_party', "
        f"'2026-07-06T17:00:00-04:00', '{SOURCE_ID}', "
        f"{sql_text('Deadline #1 for non-principal party candidates; principal party nominees come from the primary')}),\n"
        f"  ('{GENERAL_ELECTION_ID}', 'early_voting_start', '2026-10-22T07:00:00-04:00', '{SOURCE_ID}', null),\n"
        f"  ('{GENERAL_ELECTION_ID}', 'early_voting_end', '2026-10-29T20:00:00-04:00', '{SOURCE_ID}', null),\n"
        f"  ('{GENERAL_ELECTION_ID}', 'election_day', '2026-11-03T20:00:00-04:00', '{SOURCE_ID}', "
        f"{sql_text('polls close 8pm; ballot NOT YET certified as of 2026-07-02, see docs/election-research-notes.md')})\n"
        "on conflict (election_id, deadline_type) do nothing;\n\n"
    )

    print("Done.", file=sys.stderr)


if __name__ == "__main__":
    main()
