"""Loads the 14 real, official early voting centers for Montgomery County,
MD, 2026 primary election into polling_locations. Transcribed from the MSBE
certified PDF (Montgomery County section, "14 centers" -- count matches
exactly what's transcribed below):
https://elections.maryland.gov/elections/2026/2026_Early_Voting_Centers-EN.pdf

Geocodes each address with the same Census geocoder used by the search/
sample-ballot Edge Functions, so precision is consistent with the rest of
the pipeline.

Usage:
    python3 scripts/load_montgomery_early_voting_2026_primary.py > out.sql
"""
import json
import sys
import time
import urllib.parse
import urllib.request

SOURCE_URL = "https://elections.maryland.gov/elections/2026/2026_Early_Voting_Centers-EN.pdf"
SOURCE_ID = "66666666-6666-6666-6666-666666666666"
PRIMARY_ELECTION_ID = "22222222-2222-2222-2222-222222222222"

CENTERS = [
    ("Activity Center at Bohrer Park", "506 S. Frederick Avenue", "Gaithersburg", "20877"),
    ("Bauer Drive Community Recreation Center", "14625 Bauer Drive", "Rockville", "20853"),
    ("Damascus Community Recreation Center", "25520 Oak Drive", "Damascus", "20872"),
    ("Germantown Community Recreation Center", "18905 Kingsview Road", "Germantown", "20874"),
    ("Isiah \"Ike\" Leggett Executive Office Building", "101 Monroe Street", "Rockville", "20850"),
    ("Jane E. Lawton Community Recreation Center", "4301 Willow Lane", "Chevy Chase", "20815"),
    ("Marilyn J. Praisner Community Recreation Center", "14906 Old Columbia Pike", "Burtonsville", "20866"),
    ("Mid-County Community Recreation Center", "2004 Queensguard Road", "Silver Spring", "20906"),
    ("Nancy H. Dacek North Potomac Community Rec Center", "13850 Travilah Road", "Rockville", "20850"),
    ("Potomac Community Recreation Center", "11315 Falls Road", "Potomac", "20854"),
    ("Sandy Spring Volunteer Fire Department - The Ballroom", "17921 Brooke Road", "Sandy Spring", "20860"),
    ("Silver Spring Civic Building", "One Veterans Place", "Silver Spring", "20910"),
    ("Wheaton Library & Community Recreation Center", "11701 Georgia Avenue", "Wheaton", "20902"),
    ("White Oak Community Recreation Center", "1700 April Lane", "Silver Spring", "20904"),
]


def geocode_census(address: str):
    url = "https://geocoding.geo.census.gov/geocoder/locations/onelineaddress?" + urllib.parse.urlencode(
        {"address": address, "benchmark": "Public_AR_Current", "format": "json"}
    )
    with urllib.request.urlopen(url, timeout=30) as resp:
        data = json.load(resp)
    matches = data.get("result", {}).get("addressMatches", [])
    if matches:
        coords = matches[0]["coordinates"]
        return coords["y"], coords["x"]
    return None, None


def geocode_arcgis(address: str):
    url = "https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/findAddressCandidates?" + urllib.parse.urlencode(
        {"f": "json", "singleLine": address, "countryCode": "USA", "maxLocations": "1"}
    )
    with urllib.request.urlopen(url, timeout=30) as resp:
        data = json.load(resp)
    candidates = data.get("candidates", [])
    if candidates:
        loc = candidates[0]["location"]
        return loc["y"], loc["x"]
    return None, None


def geocode(street: str, city: str, zip5: str):
    address = f"{street}, {city}, MD {zip5}"
    for attempt in range(3):
        try:
            lat, lon = geocode_census(address)
            if lat is not None:
                return lat, lon
            break  # no match, no point retrying the same query
        except Exception as e:
            print(f"  retry Census geocoding {address}: {e}", file=sys.stderr)
            time.sleep(2)

    for attempt in range(3):
        try:
            lat, lon = geocode_arcgis(address)
            if lat is not None:
                return lat, lon
            return None, None
        except Exception as e:
            print(f"  retry ArcGIS geocoding {address}: {e}", file=sys.stderr)
            time.sleep(2)
    return None, None


def dq(value: str, tag: str = "q") -> str:
    return f"${tag}${value}${tag}$"


def sql_text(value):
    return "null" if value is None else dq(str(value))


def main():
    out = sys.stdout
    out.write("-- Generated by scripts/load_montgomery_early_voting_2026_primary.py. Idempotent: safe to re-run.\n\n")

    out.write(
        "insert into sources (source_id, source_url, source_type, effective_date, confidence, notes)\n"
        f"values ('{SOURCE_ID}', {sql_text(SOURCE_URL)}, {sql_text('early_voting_centers_pdf')}, "
        f"'2026-04-23', 1.0, {sql_text('MSBE certified early voting centers list, Montgomery County section')})\n"
        "on conflict (source_id) do nothing;\n\n"
    )

    for name, street, city, zip5 in CENTERS:
        lat, lon = geocode(street, city, zip5)
        print(f"{name}: {lat}, {lon}", file=sys.stderr)
        geom_sql = (
            f"st_setsrid(st_makepoint({lon}, {lat}), 4326)" if lat is not None and lon is not None else "null"
        )
        address_json = json.dumps({"street": street, "city": city, "state": "MD", "zip5": zip5})
        out.write(
            "insert into polling_locations (election_id, location_type, name, address, geom, hours, "
            "start_date, end_date, source_id)\n"
            f"select '{PRIMARY_ELECTION_ID}', 'early_vote', {sql_text(name)}, {dq(address_json, 'j')}::jsonb, "
            f"{geom_sql}, {sql_text('7:00 AM - 8:00 PM')}, '2026-06-11', '2026-06-18', '{SOURCE_ID}'\n"
            "where not exists (\n"
            "  select 1 from polling_locations existing\n"
            f"  where existing.election_id = '{PRIMARY_ELECTION_ID}' and existing.name = {sql_text(name)}\n"
            ");\n\n"
        )

    print("Done.", file=sys.stderr)


if __name__ == "__main__":
    main()
